package com.example.jdbcdemo.service;

import java.util.List;
import java.sql.*;
import com.example.jdbcdemo.domain.Music;


public class MusicService {

    private Connection connection;
    private String url = "jdbc:hsqldb:hsql://localhost/workdb";
    private String createTableMusic = "CREATE TABLE Music(id bigint GENERATED BY DEFAULT AS IDENTITY, autor varchar(50), title varchar(50))";
    private Statement statement;

    public MusicService(){
        try{
           connection = DriverManager.getConnection(url);
           statement = connection.createStatement();

            ResultSet resultSet = connection.getMetaData().getTables(null,null,null,null);
            boolean tableExists = false;
            while (resultSet.next()){
                if("Music".equalsIgnoreCase(resultSet.getString("table_name"))){
                    tableExists = true;
                    break;
                }
            }
            if(!tableExists){
                statement.executeUpdate(createTableMusic);
            }

        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    public void addMusic(Music music) throws SQLException {
        String addMusicSql = "INSERT INTO Music ( autor , title ) VALUES " +
                "(\'" + music.getAutor() + "\' ,\'" + music.getTitle() + "\')";
        statement.executeUpdate(addMusicSql);
    }

}
